module.exports = {
	addDescription: 'Elemek hozzáadása',
	addUserDescription: 'Felhasználó hozzáadása',
	addUserTeam: 'Csapatnév',
	addUserFirstname: 'Keresztnév',
	addUserLastname: 'Vezetéknév',
	addUserEmail: 'Email cím',
	addTeamDescription: 'Csapat hozzáadása',
	addTeamTeam: 'Csapatnév',
	authDescription: 'Felhasználó hitelesítése',
	authTeam: 'Csapat azonosító',
	authCode: 'Hitelesító kód',
	editDescription: 'Adatok módosítása',
	editTeamNameDescription: 'Csapatnév módosítása',
	editTeamNameOldName: 'Régi név',
	editTeamNameNewName: 'Új név',
	editRegenDescription: 'Belépési hitelesítő kód újragenerálása',
	editRegenEmail: 'Játékos email címe',
	finalistsDescription: 'Döntősök kiválasztása',
	finalistsPromoteDescription: 'Hozzáférés adása a döntős csatornákhoz',
	finalistsPromoteUser: 'Felhasználónév',
	helpDescription: 'Általános segítség',
	helpSupportDescription: 'Új hibajegy létrehozása',
	helpSupportMessage: 'Kérlek röviden (max 150 karakter) fejtsd ki a problémát, amellyel találkoztál!',
	helpCommandsDescription: 'Általad használható parancsok kiíratása',
	infoDescription: 'Adatok lekérése',
	infoUserDescription: 'Moderátori funkció',
	infoUserUser: 'Felhasználónév',
	infoTeammatesDescription: 'Moderátori funkció',
	infoTeammatesUser: 'Felhasználónév',
	lockDescription: 'Funkciók lezárása',
	lockAuthDescription: 'Auth funkció letiltása',
	lockSupportDescription: 'Support funkció letiltása',
	lockSupportCompDescription: 'Support funkció lezárása a selejtezősök számára',
	lockSubmitDescription: 'Submit funkció lezárása',
	myDescription: 'Adatok lekérése',
	myTeamDescription: 'Saját csapattársak lekérdezése',
	myTicketDescription: 'Saját hibajegyek lekérdezése',
	pingDescription: 'Eléretőség tesztelése',
	pingWsDescription: 'Websocket teszt',
	pingFullDescription: 'Websocket és roundtrip teszt',
	pruneDescription: 'Több üzenet törlése',
	pruneAmount: 'Üzenetek mennyisége számban',
	removeDescription: 'Elemek eltávolítása',
	removeUserDescription: 'Felhasználó eltávolítása',
	removeUserUser: 'Email cím',
	removeTeamDescription: 'Csapat eltávolítása',
	removeTeamTeam: 'Csapatnév',
	removeKvDescription: 'kv store pruge',
	removeKvChannelsDescription: 'Csatornák törlése a kv store-ból',
	removeKvRolesDescription: 'Privilégiumok törlése a kv store-ból',
	removeKvTicketDescription: 'Ticket eltávolítása a kv store-ból',
	removeKvTicketTicket: 'Ticket ID',
	removeAuthUnbanDescription: 'Auth ban eltávolítása',
	removeAuthUnbanUser: 'User ID',
	removeSlashDescription: 'Összes parancs eltávolítása',
	submitDescription: 'Flag ellenőrzése',
	submitString: 'Flag',
	supportDescription: 'Technikai segítségnyújtás',
	supportClearDescription: 'Support csatrona tartalma kitörlése',
	supportClearSlot: 'Slot',
	supportClaimDescription: 'Ticket felvétele',
	supportClaimTicket: 'Ticket ID',
	supportClaimSlot: 'Slot',
	supportCloseDescription: 'Ticket lezárása',
	supportCloseTicket: 'Ticket ID',
	supportNrkDescription: 'Nem releváns kérdés',
	supportNrkTicket: 'Ticket ID',
	supportBanDescription: 'Support tiltása a felhasználónak',
	supportBanUser: 'Felhasználónév',
	supportUnbanDescription: 'Support tiltás feloldása a felhasználónak',
	supportUnbanUser: 'Felhasználónév',
	unlockDescription: 'Funkciók feloldása',
	unlockAuthDescription: 'Auth funkció feloldása',
	unlockSupportDescription: 'Support funkció feloldása',
	unlockSupportCompDescription: 'Support funkció feloldása a selejtezősök számára',
	unlockSubmitDescription: 'Submit funkció feloldása',
	warnDescription: 'Figyelmeztetés',
	warnUserDescription: 'Felhasználó figyelmeztetése',
	warnUserUser: 'Felhasználónév',
	warnTeamDescription: 'Csapat figyelmeztetése',
	warnTeamUser: 'Felhasználónév',
};